- name: Deploy to Firebase Hosting
  uses: FirebaseExtended/action-hosting-deploy@v0
  with:
    # Esta es la línea que te falta:
    firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT }}'
    
    # Asegúrate también de tener el token del repo:
    repoToken: '${{ secrets.GITHUB_TOKEN }}'
    
    # Opcional pero recomendado (asegura el proyecto correcto):
    projectId: tu-id-de-proyecto-firebase